export { getCurrentPosition } from './lib/geo'
export { triggerHaptic } from './lib/haptics'
export { openExternalUrl } from './lib/browser'
export { shareContent } from './lib/share'
export type { ShareContentOptions, ShareContentResult } from './lib/share'
export { copyToClipboard } from './lib/clipboard'
export { useNetworkStatus } from './lib/network'
export { storage } from './lib/preferences'
export { initializeCapacitor } from './lib/init'
export { isAndroid, isIOS, isNative } from './lib/init'
export { isNfcCardScanSupported, scanCardUidOnce } from './lib/nfc'
export { NfcScanError } from './lib/nfc'
export type { NfcScanFailureReason } from './lib/nfc'
export { notify } from './lib/notifications'
